name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl --request POST \
        --url https://api.render.com/v1/services/srv-csu8ma0gph6c7387teb0/deploys \
        --header 'accept: application/json' \
        --header "authorization: Bearer ${RENDER_API_KEY}" \
        --header 'content-type: application/json'